%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/morri361/md/combined_gp28/redo/depthplot.dat
%
% Auto-generated by MATLAB on 09-Dec-2022 16:41:04

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 57);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "res_1", "res_2", "res_3", "res_4", "res_5", "res_6", "res_7", "res_8", "res_9", "res_10", "res_11", "res_12", "res_13", "res_14", "res_15", "res_16", "res_17", "res_18", "res_19", "res_20", "res_21", "res_22", "res_23", "res_24", "res_25", "res_26", "res_27", "res_28", "res_29", "res_30", "res_31", "res_32", "res_33", "res_34", "res_35", "res_36", "res_37", "res_38", "res_39", "res_40", "res_41", "res_42", "res_43", "res_44", "res_45", "res_46", "res_47", "res_48", "res_49", "res_50", "res_51", "res_52", "res_53", "res_54", "res_55", "res_56"];
opts.SelectedVariableNames = ["res_1", "res_2", "res_3", "res_4", "res_5", "res_6", "res_7", "res_8", "res_9", "res_10", "res_11", "res_12", "res_13", "res_14", "res_15", "res_16", "res_17", "res_18", "res_19", "res_20", "res_21", "res_22", "res_23", "res_24", "res_25", "res_26", "res_27", "res_28", "res_29", "res_30", "res_31", "res_32", "res_33", "res_34", "res_35", "res_36", "res_37", "res_38", "res_39", "res_40", "res_41", "res_42", "res_43", "res_44", "res_45", "res_46", "res_47", "res_48", "res_49", "res_50", "res_51", "res_52", "res_53", "res_54", "res_55", "res_56"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
d = readtable(uigetfile("*.dat"), opts);

%% Convert to output type
d = table2array(d);

%% Clear temporary variables
clear opts;

[m,n]= size(d);
for i=1:n
    err(i)= std(d(:,i))
    avgdepth(i)=mean(d(:,i));
end

h = errorbar(1:n,avgdepth, err);
