clear all;
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/morri361/figures/SCN-NC3-SCP-PO4-contact-4-A-cutoff-1rep.dat
%
% Auto-generated by MATLAB on 16-Dec-2022 11:30:29

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 34);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "SER2SCN", "ASP13SCN", "THR15SCN", "ASP17SCN", "THR21SCN", "ASN40SCN", "GLN41SCN", "SER42SCN", "ASP44SCN", "ASP47SCN", "THR48SCN", "THR53SCN", "ASN56SCN", "SER2SCP", "LYS3SCP", "LYS5SCP", "LYS6SCP", "THR15SCP", "LYS16SCP", "THR21SCP", "ARG24SCP", "ARG33SCP", "LYS34SCP", "ARG37SCP", "ASN40SCP", "GLN41SCP", "SER42SCP", "THR48SCP", "LYS51SCP", "THR53SCP", "LYS54SCP", "LYS55SCP", "ASN56SCP"];
opts.SelectedVariableNames = ["SER2SCN", "ASP13SCN", "THR15SCN", "ASP17SCN", "THR21SCN", "ASN40SCN", "GLN41SCN", "SER42SCN", "ASP44SCN", "ASP47SCN", "THR48SCN", "THR53SCN", "ASN56SCN", "SER2SCP", "LYS3SCP", "LYS5SCP", "LYS6SCP", "THR15SCP", "LYS16SCP", "THR21SCP", "ARG24SCP", "ARG33SCP", "LYS34SCP", "ARG37SCP", "ASN40SCP", "GLN41SCP", "SER42SCP", "THR48SCP", "LYS51SCP", "THR53SCP", "LYS54SCP", "LYS55SCP", "ASN56SCP"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
rep1 = readtable(uigetfile("*.dat"), opts);


%% Clear temporary variables
clear opts

SCN_NC3 = stackedplot(rep1(:,1:13));
SCP_PO4_H1 = figure;
SCP_PO4_H1 = stackedplot(rep1(:,14:19));
SCP_PO4_H2 = figure;
SCP_PO4_H2 = stackedplot(rep1(:,20:25));
SCP_PO4_H3 = figure;
SCP_PO4_H3 = stackedplot(rep1(:,26:end));

